/*
 * Node API
 * query node counts and pre-launch nodes
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gridlastic.grid.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * RequestPreset
 */
public class RequestPreset {
    public static final String SERIALIZED_NAME_NODES = "nodes";
    @SerializedName(SERIALIZED_NAME_NODES)
    private List<PresetParams> nodes = null;

    public RequestPreset() {
    }

    public RequestPreset nodes(List<PresetParams> nodes) {

        this.nodes = nodes;
        return this;
    }

    public RequestPreset addNodesItem(PresetParams nodesItem) {
        if (this.nodes == null) {
            this.nodes = new ArrayList<PresetParams>();
        }
        this.nodes.add(nodesItem);
        return this;
    }

    /**
     * Get nodes
     *
     * @return nodes
     **/
    @javax.annotation.Nullable
    public List<PresetParams> getNodes() {
        return nodes;
    }


    public void setNodes(List<PresetParams> nodes) {
        this.nodes = nodes;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RequestPreset requestPreset = (RequestPreset) o;
        return Objects.equals(this.nodes, requestPreset.nodes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nodes);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RequestPreset {\n");
        sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

